### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by jpopelka** [asottile/setup-cfg-fmt#25] opened 2020-02-04 15:09 UTC
Hi,

I like the tool and would like to use it in `pre-commit`, but it removes comments (lines starting with `#`) from my `setup.cfg`.

I know the support won't be that easy since `ConfigParser` doesn't keep the comments in a structure.

**Comment by asottile** [comment] 2020-02-04 15:10
duplicate of #21 - afaik it's intractable

**Closed by asottile** 2020-02-04 15:10 UTC

**Comment by glensc** [comment] 2022-11-10 16:20
I've reconsidered my pro-tip of line based staging and undo comment changes:
- https://github.com/asottile/setup-cfg-fmt/pull/21#issuecomment-1135513559

it's extremely annoying when rebasing say 50+ commits and have to undo the changes for each commit. so removing the hook in my project:
- https://github.com/Taxel/PlexTraktSync/pull/1187

for future me, you used these command:

```
git diff setup.cfg|patch -R -p1 && git rebase --continue && pre-commit run --all-files
```
